### ISSUE TITLE
waf test failing after tinymt change

### ISSUE THREAD

**Issue by Colin-Suckow** [pebble-dev/pebble-firmware#97]
`waf test` fails to compile many of the files within `src/fw` because tinymt isn't being included correctly when build with the 'test' variant. Presumably this was caused by 383d889, but I haven't done a bisection or anything to verify.

One example of an error message from `waf test`.
```
[ 3713/16906] Compiling src/fw/applib/graphics/text_layout.c
../../src/fw/util/rand/rand.c:38:10: fatal error: 'tinymt32.h' file not found
   38 | #include "tinymt32.h"
      |          ^~~~~~~~~~~~
1 error generated.
```

The test workflow needs to be updated too. The pipeline is reporting tests as all green because I suppressed the results due to the ~10 failing unit tests. Unfortunately that suppression wasn't smart enough to notice that 0 tests were run. The workflow should be able to detect and fail in this situation.

**Comment by gmarull** [comment]
This has been fixed
